### ISSUE TITLE
Roadmap for 2017

### ISSUE THREAD

**Issue by solody** [weeshop/WeeShop#1]
- [x] drupal commerce 2.x 集成

- [x] 添加示例产品数据 

- [x] 集成search_api模块，实现产品搜索功能

- [x] 创建pc端主题 

- [ ] 集成支付宝和微信支付网关

- [ ] 翻译drupal commerce 2.x中文界面

- [x] 集成Oauth2 API认证功能

- [ ] 通过手机号注册用户
- [ ] 使用微信登录
- [ ] 轮播图
